# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Set working directory
WORKDIR /app

# Copy package files and tsconfig to leverage Docker cache
COPY package.json package-lock.json tsconfig.json ./

# Install dependencies without running scripts for faster install
RUN npm install --ignore-scripts

# Copy rest of the source code
COPY . .

# Run build step
RUN npm run build

# Expose port if needed for HTTP mode (default port from code may be 3000, adjust as needed)
EXPOSE 3000

# Default command: run in stdio mode
CMD ["node", "dist/index.js", "--stdio"]
